### PR TITLE
Update paas documentation with new processes

### PR DESCRIPTION
**Pull request by saliceti**
## What
Management of DfE paas is being migrated to Infrastructure Operations

### CODE REVIEW

**Review by AshiqaliDamani — COMMENTED** [review]
[Line 34] ‘The strategic Azure platform may take time and resource to set up’ should this also read ‘Traditional’ instead of strategic also ?

**Comment by saliceti** [comment]
> [Line 34] ‘The strategic Azure platform may take time and resource to set up’ should this also read ‘Traditional’ instead of strategic also ?

Fixed, thanks

**Review by AshiqaliDamani — APPROVED** [review]
Fine with updates

**Comment by saliceti** [comment]
[Update paas tech guidance](https://trello.com/c/3maTh46S/244-update-paas-tech-guidance)

**Pull request merged**
