### PR TITLE
Continuous delivery guide

### PR DESCRIPTION
**Pull request by saliceti**

### CODE REVIEW

**Comment by saliceti** [comment]
[Guidance on CI/CD](https://trello.com/c/L07tcWzC/215-guidance-on-ci-cd)

**Review by aje54 — CHANGES_REQUESTED** [review]
The content is good. It would be good to additionally have have some practical information in here too, for example tool set examples, real examples from TS of how continuous deployment has been implemented.

**Comment by saliceti** [comment]
> The content is good. It would be good to additionally have have some practical information in here too, for example tool set examples, real examples from TS of how continuous deployment has been implemented.

@aje54 I've added examples and more detail about the tools

**Review by aje54 — APPROVED** [review]
Looks good.

**Pull request merged**
